name: Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
     branches: [ "master"]
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
       with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1
          
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
       
     - name: Build Image
       run: | 
          docker image build -t webmagic1/flaskapp:v1 .

     - name: Tag Image
       run: | 
         docker tag webmagic1/flaskapp:v1 938336822495.dkr.ecr.us-east-1.amazonaws.com/python-app:v1
    
     - name: Push Image
       run:  
          docker push 938336822495.dkr.ecr.us-east-1.amazonaws.com/python-app:v1
          

    
   
